name: Setup .NET
    description: Gemeinsame Schritte zum Checkout und .NET-Setup

runs:
  using: "composite"
  steps:
      uses: actions/checkout@v4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET Dependencies
      run: dotnet restore