name: DartZone
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET Dependencies
      run: dotnet restore
    
    - name: Build .NET Project
      run: |
        DOTNET_BUILD="dotnet build --no-restore -c Release"
        $DOTNET_BUILD ./API/API.csproj
        $DOTNET_BUILD ./Shared/Shared.csproj