name: DartZone
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet
    
    - name: Build .NET Project
      run: |
        DOTNET_BUILD="dotnet build --no-restore -c Release"
        $DOTNET_BUILD ./API/API.csproj
        $DOTNET_BUILD ./Shared/Shared.csproj

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: ./.github/actions/setup-dotnet

    - name: Run Tests
      run: dotnet test --collect:"XPlat Code Coverage"